name: Deploy to Firebase

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '12.22.12'
            - name: Setup the code
              run: npm install --legacy-peer-deps
            - name: Deploy to Firebase
              uses: mohammed-atif/firebase-publish-react@v1.0
              env:
                  REACT_APP_API_KEY: ${{secrets.FSTG_EDB94_REACT_APP_API_KEY}}
                  REACT_APP_AUTH_DOMAIN: ${{secrets.FSTG_EDB94_REACT_APP_AUTH_DOMAIN}}
                  REACT_APP_PROJECT_ID: ${{secrets.FSTG_EDB94_REACT_APP_PROJECT_ID}}
                  REACT_APP_STORAGE_BUCKET: ${{secrets.FSTG_EDB94_REACT_APP_STORAGE_BUCKET}}
                  REACT_APP_MESSAGING_SENDER_ID: ${{secrets.FSTG_EDB94_REACT_APP_MESSAGING_SENDER_ID}}
                  REACT_APP_APP_ID: ${{secrets.FSTG_EDB94_REACT_APP_APP_ID}}
                  REACT_APP_MEASUREMENT_ID: ${{secrets.FSTG_EDB94_REACT_APP_MEASUREMENT_ID}}
              with:
                  firebase-token: ${{ secrets.FIREBASE_TOKEN }}
                  node-version: '12.22.12'
