name: Issue Agent Branch

on:
  issues:
    types: [labeled]

jobs:
  create-branch:
    if: github.event.label.name == 'agent-task'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # so we can branch from latest main

      - name: Set up branch name
        id: vars
        run: |
          # Lowercase, replace spaces with dashes, strip non-alphanum
          SAFE_TITLE=$(echo "${{ github.event.issue.title }}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-' | cut -c1-30)
          echo "BRANCH_NAME=agent/${{ github.event.issue.number }}-${SAFE_TITLE}" >> $GITHUB_ENV

      - name: Create and push branch
        run: |
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
