name: Run all tests

on:
    pull_request:
        branches:
            - main

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
            - name: Setup the code
              run: npm install
            - name: Test the code
              run: npm test

    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
            - name: Setup the code
              run: npm install
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v2
              env:
                  REACT_APP_API_KEY: ${{secrets.FSTG_EDB94_REACT_APP_API_KEY}}
                  REACT_APP_AUTH_DOMAIN: ${{secrets.FSTG_EDB94_REACT_APP_AUTH_DOMAIN}}
                  REACT_APP_PROJECT_ID: ${{secrets.FSTG_EDB94_REACT_APP_PROJECT_ID}}
                  REACT_APP_STORAGE_BUCKET: ${{secrets.FSTG_EDB94_REACT_APP_STORAGE_BUCKET}}
                  REACT_APP_MESSAGING_SENDER_ID: ${{secrets.FSTG_EDB94_REACT_APP_MESSAGING_SENDER_ID}}
                  REACT_APP_APP_ID: ${{secrets.FSTG_EDB94_REACT_APP_APP_ID}}
                  REACT_APP_MEASUREMENT_ID: ${{secrets.FSTG_EDB94_REACT_APP_MEASUREMENT_ID}}
              with:
                  spec: cypress/integration/fstg/**/*spec.ts
                  start: npm start
                  browser: chrome
                  headless: true
                  wait-on: 'http://localhost:3000'
