name: Run all tests

on:
    pull_request:
        branches:
            - main

jobs:
    run-all-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
            - name: Setup the code
              run: npm install
            - name: Test the code
              run: npm test
